# Generated by Django 5.2.4 on 2025-08-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Is Need?'),
        ),
    ]
